name: Update docs index

on:
  push:
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate index
        run: python scripts/generate_index.py
      
      # debug1
      #- name: Debug after generate
      #  run: |
      #    echo "==== AFTER GENERATE ===="
      #    ls -l
      #    echo "---- index.html ----"
      #    cat index.html || echo "index.html not found"

      # debug2
      #- name: Debug git status
      #  run: |
      #    echo "==== GIT STATUS ===="
      #    git status
      #    echo "==== GIT DIFF ===="
      #    git diff

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add index.html

          echo "==== BEFORE COMMIT ===="
          git status

          git commit -m "Update index" || echo "No changes"

          echo "==== AFTER COMMIT ===="
          git status

          git push